# Generated by Django 3.2.9 on 2021-11-23 10:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('start_time', models.DateField()),
                ('length', models.DurationField()),
                ('link', models.URLField(default='localhost')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=150)),
                ('ballon_color', models.CharField(max_length=150)),
                ('point', models.SmallIntegerField()),
                ('time_limit', models.SmallIntegerField()),
                ('memory_limit', models.SmallIntegerField()),
                ('description', ckeditor.fields.RichTextField()),
                ('additional_note', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('constraints', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('input_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('output_description', ckeditor.fields.RichTextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='core.contest')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='core.contest')),
            ],
        ),
        migrations.CreateModel(
            name='SampleOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_outputs', to='core.problem')),
            ],
        ),
        migrations.CreateModel(
            name='SampleInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_inputs', to='core.problem')),
            ],
        ),
    ]
